"""Reviewed Russian translations for English source messages."""
RUSSIAN = {'Junk': 'Спам',
 'Sent': 'Отправленные',
 'Drafts': 'Черновики',
 'Deleted': 'Корзина',
 'Missing client_id or refresh_token': 'Не указан client_id или refresh_token',
 'Error': 'Ошибка',
 'Connected': 'Подключено',
 'Retrieved successfully': 'Данные получены',
 'Marked successfully': 'Метка изменена',
 'Sent successfully': 'Отправлено',
 'Deleted successfully': 'Удалено',
 'Normal': 'Работает',
 'Failed to retrieve messages': 'Не удалось получить письма',
 'OAuth2 error: ': 'Ошибка OAuth2: ',
 'Network error: ': 'Ошибка сети: ',
 'Connection failed: ': 'Ошибка подключения: ',
 'API error: ': 'Ошибка API: ',
 'Cannot open folder ': 'Не удалось открыть папку ',
 'Failed to retrieve messages: ': 'Не удалось получить письма: ',
 'Marking failed: ': 'Не удалось изменить метку: ',
 'Failed to retrieve attachments: ': 'Не удалось получить вложения: ',
 'Sending failed: ': 'Не удалось отправить: ',
 'Authentication failed: ': 'Ошибка авторизации: ',
 'SMTP error: ': 'Ошибка SMTP: ',
 'Deletion failed: ': 'Не удалось удалить: ',
 'Token is valid': 'Токен действителен',
 '(No subject)': '(Без темы)',
 'Failed to save new refresh_token: ': 'Не удалось сохранить новый refresh_token: ',
 'Opening the authorization page. Please sign in...': 'Открывается страница авторизации. Войдите в аккаунт...',
 'Waiting for sign-in...': 'Ожидание входа...',
 'Authorization timed out': 'Время ожидания авторизации истекло',
 'Obtaining token...': 'Получение токена...',
 'Browser initialization failed: ': 'Не удалось запустить браузер: ',
 'No refresh_token returned': 'Сервер не вернул refresh_token',
 'Failed to obtain token: ': 'Не удалось получить токен: ',
 'Authorization error: ': 'Ошибка авторизации: ',
 'Browser was closed': 'Браузер закрыт',
 'Authorization failed: ': 'Не удалось авторизоваться: ',
 'Authorization code received!': 'Код авторизации получен!',
 'Authorization failed': 'Ошибка авторизации',
 'Default': 'По умолчанию',
 'Standard': 'Обычный',
 'Added successfully': 'Добавлено',
 'Email already exists': 'Этот адрес уже добавлен',
 'Inbox': 'Входящие',
 'OK': 'ОК',
 'Account details': 'Данные аккаунта',
 '🔐 Basic information': '🔐 Основные сведения',
 '🌐 Server settings': '🌐 Настройки серверов',
 'Yes': 'Да',
 'No': 'Нет',
 '📋 Other information': '📋 Дополнительные сведения',
 'Copy all information': 'Копировать все данные',
 'Close': 'Закрыть',
 'Notice': 'Уведомление',
 'Copied to clipboard': 'Скопировано в буфер обмена',
 'All information copied to clipboard': 'Все данные скопированы в буфер обмена',
 'Import accounts': 'Импорт аккаунтов',
 'Import email accounts': 'Импорт почтовых аккаунтов',
 'One account per line: email----password----client_id----refresh_token. For password-only accounts: email----password.': 'Один '
                                                                                                                          'аккаунт '
                                                                                                                          'на '
                                                                                                                          'строку: '
                                                                                                                          'email----пароль----client_id----refresh_token. '
                                                                                                                          'Без '
                                                                                                                          'токена: '
                                                                                                                          'email----пароль.',
 'From file': 'Из файла',
 'From clipboard': 'Из буфера обмена',
 'Skip existing email addresses': 'Пропускать уже добавленные адреса',
 'Cancel': 'Отмена',
 'Import': 'Импорт',
 'Select file': 'Выберите файл',
 'Text files (*.txt);;All files (*.*)': 'Текстовые файлы (*.txt);;Все файлы (*.*)',
 'Successful: ': 'Успешно: ',
 ' | Failed: ': ' | Ошибок: ',
 ' account(s)': ' аккаунт(ов)',
 'Import complete': 'Импорт завершён',
 'Refresh': 'Обновить',
 'Search messages...': 'Поиск писем...',
 'Compose': 'Написать',
 'Reply': 'Ответить',
 'Forward': 'Переслать',
 'Mark': 'Отметить',
 'Delete': 'Удалить',
 'Loading...': 'Загрузка...',
 'Select a message to view': 'Выберите письмо для просмотра',
 'Attachments:': 'Вложения:',
 'Select destination folder': 'Выберите папку для сохранения',
 'Save attachment': 'Сохранить вложение',
 'read': 'прочитанное',
 'unread': 'непрочитанное',
 '\n\n\n-------- Original message --------\nFrom: ': '\n\n\n-------- Исходное письмо --------\nОт: ',
 '\nDate: ': '\nДата: ',
 '\n\n\n-------- Forwarded message --------\nFrom: ': '\n\n\n-------- Пересланное письмо --------\nОт: ',
 '\nSubject: ': '\nТема: ',
 'Forward message': 'Переслать письмо',
 'From:': 'От:',
 'To:': 'Кому:',
 'Separate recipients with commas': 'Разделяйте адреса запятыми',
 'Cc:': 'Копия:',
 'Optional; separate addresses with commas': 'Необязательно; разделяйте адреса запятыми',
 'Subject:': 'Тема:',
 'Message subject': 'Тема письма',
 'Add attachment': 'Добавить вложение',
 'Message:': 'Текст:',
 'Enter your message here...': 'Введите текст письма...',
 'Send': 'Отправить',
 'Select attachments': 'Выберите вложения',
 'All files (*.*)': 'Все файлы (*.*)',
 'Sending...': 'Отправка...',
 'Sending message...': 'Отправка письма...',
 'All accounts will send to these recipients; separate addresses with commas': 'Все аккаунты отправят письма этим '
                                                                               'получателям; разделяйте адреса '
                                                                               'запятыми',
 'Sending progress:': 'Ход отправки:',
 'Confirm sending': 'Подтверждение отправки',
 '✓ Success': '✓ Успешно',
 'Sending complete': 'Отправка завершена',
 'Manual OAuth2 authorization': 'Авторизация OAuth2',
 '🔐 Manual OAuth2 authorization': '🔐 Авторизация OAuth2',
 'Click "Start authorization" to open the Microsoft sign-in page.\nSign in to your Outlook account; the app will then obtain the authorization details.': 'Нажмите '
                                                                                                                                                          '«Начать '
                                                                                                                                                          'авторизацию», '
                                                                                                                                                          'чтобы '
                                                                                                                                                          'открыть '
                                                                                                                                                          'страницу '
                                                                                                                                                          'входа '
                                                                                                                                                          'Microsoft.\n'
                                                                                                                                                          'Войдите '
                                                                                                                                                          'в '
                                                                                                                                                          'свой '
                                                                                                                                                          'аккаунт '
                                                                                                                                                          'Outlook; '
                                                                                                                                                          'программа '
                                                                                                                                                          'получит '
                                                                                                                                                          'данные '
                                                                                                                                                          'авторизации.',
 '💡 Wait for the automatic redirect after sign-in. Do not close the browser manually.': '💡 После входа дождитесь '
                                                                                        'автоматического '
                                                                                        'перехода. Не закрывайте '
                                                                                        'браузер вручную.',
 'Ready': 'Готово',
 'Authorization result:': 'Результат авторизации:',
 'Start authorization': 'Начать авторизацию',
 'Stop': 'Остановить',
 'Opening browser...': 'Запуск браузера...',
 'Sign in to your Outlook account in the browser': 'Войдите в аккаунт Outlook в браузере',
 'Stopped': 'Остановлено',
 '🔑 OAuth2 credentials': '🔑 Данные OAuth2',
 'Email address: ': 'Адрес почты: ',
 'Password: ': 'Пароль: ',
 'Group: ': 'Группа: ',
 'Status: ': 'Статус: ',
 'Type: ': 'Тип: ',
 'Import into group:': 'Импортировать в группу:',
 'Clipboard is empty or contains no text': 'Буфер обмена пуст или не содержит текста',
 'Enter account information': 'Введите данные аккаунта',
 ' | Skipped: ': ' | Пропущено: ',
 'Messages — ': 'Письма — ',
 'Mark as unread': 'Отметить непрочитанным',
 'From: ': 'От: ',
 'Success': 'Готово',
 'Partially completed': 'Выполнено частично',
 'Marking (0/': 'Изменение меток (0/',
 'Marking (': 'Изменение меток (',
 'Confirm deletion': 'Подтверждение удаления',
 'Delete this message?': 'Удалить это письмо?',
 'Deleting...': 'Удаление...',
 'Confirm deleting messages': 'Подтверждение удаления писем',
 'Deleting (': 'Удаление (',
 'Message deleted': 'Письмо удалено',
 'Deletion failed': 'Не удалось удалить',
 'Compose — ': 'Новое письмо — ',
 'Reply to message': 'Ответить на письмо',
 'Enter a recipient address': 'Введите адрес получателя',
 'Enter a message subject': 'Введите тему письма',
 'Message sent successfully!': 'Письмо отправлено!',
 'Sending failed': 'Не удалось отправить',
 'Send messages — ': 'Отправка писем — ',
 ' accounts': ' аккаунтов',
 'Send messages (': 'Отправка писем (',
 ' sender accounts)': ' аккаунтов отправителей)',
 'Sender accounts: ': 'Аккаунты отправителей: ',
 'Send (': 'Отправить (',
 ' messages)': ' писем)',
 'Send messages using ': 'Отправить письма с ',
 ' accounts?': ' аккаунтов?',
 '✗ Failed: ': '✗ Ошибка: ',
 'Sending... (': 'Отправка... (',
 'Complete. Sent: ': 'Завершено. Отправлено: ',
 '; failed: ': '; ошибок: ',
 ' messages': ' писем',
 'Sending complete!\nSuccessful: ': 'Отправка завершена!\nУспешно: ',
 '\nFailed: ': '\nОшибок: ',
 'An operation is in progress. Please wait.': 'Операция выполняется. Дождитесь завершения.',
 'Authorization successful!': 'Авторизация выполнена!',
 'Confirm': 'Подтвердить',
 'An operation is in progress. Stop and close?': 'Операция выполняется. Остановить и закрыть?',
 'Initializing browser...': 'Подготовка браузера...',
 'Browser opened. Sign in to an Outlook account...': 'Браузер открыт. Войдите в аккаунт Outlook...',
 'Retrieving account information...': 'Получение данных аккаунта...',
 'Email address': 'Адрес почты',
 'Password': 'Пароль',
 'Group': 'Группа',
 'Status': 'Статус',
 'Type': 'Тип',
 'IMAP server': 'Сервер IMAP',
 'IMAP port': 'Порт IMAP',
 'SMTP server': 'Сервер SMTP',
 'SMTP port': 'Порт SMTP',
 'Created': 'Дата добавления',
 'Last checked': 'Последняя проверка',
 'AWS verification code': 'Код подтверждения AWS',
 'Notes': 'Заметки',
 'Copy': 'Копировать',
 'IMAP server: ': 'Сервер IMAP: ',
 'IMAP port: ': 'Порт IMAP: ',
 'Notes: ': 'Заметки: ',
 ': no messages\n': ': писем нет\n',
 'Click to download this attachment': 'Нажмите для скачивания вложения',
 'Download all attachments to a selected folder': 'Скачать все вложения в выбранную папку',
 'Downloaded ': 'Скачано ',
 ' attachments to:\n': ' вложений в:\n',
 'Processing...': 'Обработка...',
 'Marked ': 'Отмечено ',
 ' messages as ': ' писем; статус: ',
 'Marking complete\nSuccessful: ': 'Метки изменены\nУспешно: ',
 'Mark as read': 'Отметить прочитанным',
 'Fwd:': 'Пересылка:',
 'Could not determine the message ID': 'Не удалось определить ID письма',
 'Delete the selected ': 'Удалить выбранные письма: ',
 ' messages?': '?',
 'Deleting (0/': 'Удаление (0/',
 'Deleted ': 'Удалено ',
 'Deletion complete\nSuccessful: ': 'Удаление завершено\nУспешно: ',
 '❌ Failed: ': '❌ Ошибка: ',
 'Added: ': 'Добавлено: ',
 ' — authorized and saved': ' — авторизация выполнена, аккаунт сохранён',
 'Could not retrieve the email address': 'Не удалось получить адрес почты',
 'Saving account: ': 'Сохранение аккаунта: ',
 'Delete (': 'Удалить (',
 'Mark (': 'Отметить (',
 '⬇ Download all (': '⬇ Скачать все (',
 'Failed to download attachment': 'Не удалось скачать вложение',
 'Mark all as read (': 'Все прочитаны (',
 'Mark all as unread (': 'Все не прочитаны (',
 'Read failed: ': 'Ошибка чтения: ',
 'Attachment saved to:\n': 'Вложение сохранено:\n',
 'Save failed: ': 'Ошибка сохранения: ',
 'All': 'Все',
 '📥 Drop to import accounts': '📥 Отпустите для импорта аккаунтов',
 '💡 Drag a TXT file into this window to import accounts': '💡 Перетащите TXT-файл в окно для импорта аккаунтов',
 'Based on Email-Manager (MIT). Russian / English edition.': 'На основе Email-Manager (MIT). Русская / английская '
                                                             'версия.',
 'Manual authorization': 'Авторизация',
 'Sign in through the browser to authorize OAuth2': 'Войдите через браузер для авторизации OAuth2',
 'Excel files (*.xlsx);;Text files (*.txt)': 'Файлы Excel (*.xlsx);;Текстовые файлы (*.txt)',
 'Email accounts': 'Почтовые аккаунты',
 'Accounts by group': 'Аккаунты по группам',
 'Accounts by status': 'Аккаунты по статусам',
 'Unchecked': 'Не проверен',
 '⊙  Details': '⊙  Подробности',
 '✉  View messages': '✉  Просмотр писем',
 '📋  Export information': '📋  Экспорт данных',
 'Account information copied to clipboard': 'Данные аккаунта скопированы в буфер обмена',
 'Double-click to edit notes': 'Дважды нажмите для редактирования заметки',
 'More actions': 'Другие действия',
 'Account already exists': 'Аккаунт уже добавлен',
 'Email': 'Почта',
 'Stopping...': 'Остановка...',
 'Checking 0/': 'Проверка 0/',
 ' (click to stop)': ' (нажмите для остановки)',
 'Checking ': 'Проверка ',
 'Clipboard is empty': 'Буфер обмена пуст',
 'Invalid clipboard format': 'Неверный формат данных в буфере обмена',
 'Total accounts': 'Всего аккаунтов',
 'Working accounts': 'Работающие аккаунты',
 'Accounts with errors': 'Аккаунты с ошибками',
 ';">🗑  Delete</span>': ';">🗑  Удалить</span>',
 'Account not found': 'Аккаунт не найден',
 'The file is empty': 'Файл пуст',
 'Account ': 'Аккаунт ',
 ' already exists. Update its OAuth2 credentials?': ' уже добавлен. Обновить данные OAuth2?',
 'Added account ': 'Добавлен аккаунт ',
 'The openpyxl library is required to export Excel files. Install the complete application bundle.': 'Для '
                                                                                                     'экспорта '
                                                                                                     'Excel нужна '
                                                                                                     'библиотека '
                                                                                                     'openpyxl. '
                                                                                                     'Установите '
                                                                                                     'полную '
                                                                                                     'сборку '
                                                                                                     'программы.',
 'Failed to read file: ': 'Не удалось прочитать файл: ',
 'Blocked': 'Заблокирован',
 'Failed': 'Ошибка',
 'Updated account ': 'Обновлены данные аккаунта ',
 ' OAuth2 credentials': ' (OAuth2)',
 'Error deleting account: ': 'Ошибка удаления аккаунта: ',
 'Verifying': 'Проверяется',
 'Verification': 'Проверка',
 'New group': 'Новая группа',
 'Enter group name:': 'Название группы:',
 'Rename group': 'Переименовать группу',
 'Enter the new group name:': 'Новое название группы:',
 'Email Manager': 'Менеджер почты',
 '  📋  All accounts': '  📋  Все аккаунты',
 '  🗝  Authorization': '  🗝  Авторизация',
 '  📈  Dashboard': '  📈  Статистика',
 '  ⚙  Settings': '  ⚙  Настройки',
 'Switch theme': 'Сменить тему',
 'Switch language': 'Сменить язык',
 '☀️  Light': '☀️  Светлая',
 '🌙  Dark': '🌙  Тёмная',
 'Русский': 'Русский',
 '✏️  Rename': '✏️  Переименовать',
 '🗑️  Delete': '🗑️  Удалить',
 'Group name cannot be empty': 'Введите название группы',
 'Group already exists. Choose another name.': 'Такая группа уже есть. Выберите другое название.',
 'RU': 'RU',
 'EN': 'EN',
 'Delete group "': 'Удалить группу «',
 '"?\nIts accounts will be moved to the default group.': '»?\nЕё аккаунты будут перемещены в группу по умолчанию.',
 'Show main window': 'Открыть главное окно',
 'Quit': 'Выйти',
 'The application was minimized to the system tray': 'Программа свёрнута в область уведомлений',
 'Failed to save new refresh_token: {0}': 'Не удалось сохранить новый refresh_token: {0}',
 'OAuth2 error: {0}': 'Ошибка OAuth2: {0}',
 'Network error: {0}': 'Ошибка сети: {0}',
 'API error: {0}': 'Ошибка API: {0}',
 'Connection failed: {0}': 'Ошибка подключения: {0}',
 'API error: {0} - {1}': 'Ошибка API: {0} - {1}',
 'Cannot open folder {0}: {1}': 'Не удалось открыть папку {0}: {1}',
 'Failed to retrieve messages: {0}': 'Не удалось получить письма: {0}',
 'Marking failed: {0}': 'Не удалось изменить метку: {0}',
 'Failed to retrieve attachments: {0}': 'Не удалось получить вложения: {0}',
 'Sending failed: {0} - {1}': 'Не удалось отправить: {0} - {1}',
 'Sending failed: {0}': 'Не удалось отправить: {0}',
 'Authentication failed: {0}': 'Ошибка авторизации: {0}',
 'SMTP error: {0}': 'Ошибка SMTP: {0}',
 'Deletion failed: {0}': 'Не удалось удалить: {0}',
 'Browser initialization failed: {0}': 'Не удалось запустить браузер: {0}',
 'Authorization failed: {0}': 'Не удалось авторизоваться: {0}',
 'Failed to obtain token: {0}': 'Не удалось получить токен: {0}',
 'Authorization error: {0}': 'Ошибка авторизации: {0}',
 'Email address: {0}': 'Адрес почты: {0}',
 'Password: {0}': 'Пароль: {0}',
 'Group: {0}': 'Группа: {0}',
 'Status: {0}': 'Статус: {0}',
 'Type: {0}': 'Тип: {0}',
 'IMAP server: {0}': 'Сервер IMAP: {0}',
 'IMAP port: {0}': 'Порт IMAP: {0}',
 'Notes: {0}': 'Заметки: {0}',
 'Read failed: {0}': 'Ошибка чтения: {0}',
 'Successful: {0} | Failed: {1} account(s)': 'Успешно: {0} | Ошибок: {1} аккаунт(ов)',
 ' | Skipped: {0} account(s)': ' | Пропущено: {0} аккаунт(ов)',
 'Messages — {0}': 'Письма — {0}',
 'Delete ({0})': 'Удалить ({0})',
 'Mark ({0})': 'Отметить ({0})',
 '{0}: no messages\n{1}': '{0}: писем нет\n{1}',
 'From: {0}\nDate: {1}': 'От: {0}\nДата: {1}',
 '⬇ Download all ({0})': '⬇ Скачать все ({0})',
 'Downloaded {0} attachments to:\n{1}': 'Скачано {0} вложений в:\n{1}',
 'Successful: {0}\nFailed: {1} account(s)': 'Успешно: {0}\nОшибок: {1} аккаунт(ов)',
 'Attachment saved to:\n{0}': 'Вложение сохранено:\n{0}',
 'Save failed: {0}': 'Ошибка сохранения: {0}',
 'Mark all as read ({0})': 'Все прочитаны ({0})',
 'Mark all as unread ({0})': 'Все не прочитаны ({0})',
 'Marking (0/{0})...': 'Изменение меток (0/{0})...',
 'Marking ({0}/{1})...': 'Изменение меток ({0}/{1})...',
 'Marked {0} messages as {1}': 'Отмечено {0} писем; статус: {1}',
 'Marking complete\nSuccessful: {0}\nFailed: {1} messages': 'Метки изменены\nУспешно: {0}\nОшибок: {1} писем',
 '\n\n\n-------- Original message --------\nFrom: {0}\nDate: {1}\n\n{2}': '\n'
                                                                          '\n'
                                                                          '\n'
                                                                          '-------- Исходное письмо --------\n'
                                                                          'От: {0}\n'
                                                                          'Дата: {1}\n'
                                                                          '\n'
                                                                          '{2}',
 '\n\n\n-------- Forwarded message --------\nFrom: {0}\nDate: {1}\nSubject: {2}\n\n{3}': '\n'
                                                                                         '\n'
                                                                                         '\n'
                                                                                         '-------- Пересланное '
                                                                                         'письмо --------\n'
                                                                                         'От: {0}\n'
                                                                                         'Дата: {1}\n'
                                                                                         'Тема: {2}\n'
                                                                                         '\n'
                                                                                         '{3}',
 'Delete the selected {0} messages?': 'Удалить выбранные письма: {0}?',
 'Deleting (0/{0})...': 'Удаление (0/{0})...',
 'Deleting ({0}/{1})...': 'Удаление ({0}/{1})...',
 'Deleted {0} messages': 'Удалено {0} писем',
 'Deletion complete\nSuccessful: {0}\nFailed: {1} messages': 'Удаление завершено\nУспешно: {0}\nОшибок: {1} писем',
 'Compose — {0}': 'Новое письмо — {0}',
 'Send messages — {0} accounts': 'Отправка писем — {0} аккаунтов',
 'Send messages ({0} sender accounts)': 'Отправка писем ({0} аккаунтов отправителей)',
 'Sender accounts: {0}{1}': 'Аккаунты отправителей: {0}{1}',
 'Send ({0} messages)': 'Отправить ({0} писем)',
 'Send messages using {0} accounts?': 'Отправить письма с {0} аккаунтов?',
 '✗ Failed: {0}': '✗ Ошибка: {0}',
 'Sending... ({0}/{1})': 'Отправка... ({0}/{1})',
 'Complete. Sent: {0}; failed: {1} messages': 'Завершено. Отправлено: {0}; ошибок: {1} писем',
 'Sending complete!\nSuccessful: {0}\nFailed: {1} messages': 'Отправка завершена!\n'
                                                             'Успешно: {0}\n'
                                                             'Ошибок: {1} писем',
 '❌ Failed: {0}': '❌ Ошибка: {0}',
 'Added: {0}': 'Добавлено: {0}',
 '✅ {0} — authorized and saved': '✅ {0} — авторизация выполнена, аккаунт сохранён',
 'Saving account: {0}': 'Сохранение аккаунта: {0}',
 'Failed to read file: {0}': 'Не удалось прочитать файл: {0}',
 'Account {0} already exists. Update its OAuth2 credentials?': 'Аккаунт {0} уже добавлен. Обновить данные OAuth2?',
 'Updated account {0} OAuth2 credentials': 'Обновлены данные аккаунта {0} (OAuth2)',
 'Added account {0}': 'Добавлен аккаунт {0}',
 'Checking 0/{0} (click to stop)': 'Проверка 0/{0} (нажмите для остановки)',
 'Checking {0}/{1} (click to stop)': 'Проверка {0}/{1} (нажмите для остановки)',
 'Error deleting account: {0}': 'Ошибка удаления аккаунта: {0}',
 '<span style="color:{0};">🗑  Delete</span>': '<span style="color:{0};">🗑  Удалить</span>',
 'Delete group "{0}"?\nIts accounts will be moved to the default group.': 'Удалить группу «{0}»?\n'
                                                                          'Её аккаунты будут перемещены в группу '
                                                                          'по умолчанию.'}
